name: MULTIPLE FILES
on:
  check_run:
    types: [completed]

permissions:
  id-token: write

jobs:
  share:
    name: Testing URL
    runs-on: ubuntu-latest
    if: ${{ github.event.check_run.name == 'SonarCloud Code Analysis' }}
    steps:
      - uses: pixee/upload-tool-results-action@3e0db9311500fa3268a60634dddfc4bafa2826a8
        with:
          pixee-api-url: https://f4wf3v81x2.execute-api.us-east-1.amazonaws.com/prod
          tool: sonar
          sonar-token: ${{ secrets.SONAR_TOKEN }}
